### ISSUE TITLE
src/code/error.lisp

### ISSUE THREAD

**Issue by wpasieka** [rtoy/cmucl#1] opened 2018-08-19 09:39 UTC
There is a bug in /src/code/error.lisp

(setf (documentation 'restart-name 'function)                                                                                                                                                
      _N"Returns the name of the given restart object.")  

_N gives it.

**Comment by rtoy** [comment] 2018-08-21 19:29
Cmucl has a special reader macro to handle this when building cmucl.  This is used to record this string in a POT file for translation.

To enable the reader, use:
```
(intl::install)
```
Note that this will change the reader table.

Finally, please file issues at https://gitlab.common-lisp.net/cmucl/cmucl/issues; issues filed here are likely to be ignored since this repo is a mirror of the official repo at https://gitlab.common-lisp.net/cmucl/cmucl.

**Comment by rtoy** [comment] 2018-08-21 19:29
Closing as WontFix; working as intended.

**Closed as completed by rtoy** 2018-08-21 19:29 UTC
